import type { AnyNode, AnyNodeId } from '@pascal-app/core'
import { useScene } from '@pascal-app/core'
import { CFSMember } from '../schema/cfs-member'
import type { CFSMemberId, CFSOpeningId, CFSSectionId, CFSWallFramingId } from '../schema/ids'
import type {
  CFSHeaderType,
  CFSMemberRole,
  CFSPoint3D,
  CFSProjectSettings,
} from '../schema/primitives'
import type { CFSWallFraming } from '../schema/cfs-wall-framing'
import type { CFSOpening } from '../schema/cfs-opening'
import type { CFSMemberLibrary, CFSSection } from '../schema/cfs-member-library'
import { getActiveLibrary, getProjectSettings } from '../store/selectors'
import { useCFS } from '../store/use-cfs'
import { withBatchedUndo } from '../store/with-batched-undo'
import {
  chordPositionFromWorld,
  isCornerOwned,
  wallDirection,
} from '../lib/corner-detect'
import {
  computeWallTrim,
  type JunctionPeer,
  type WallTrim,
} from '../lib/corner-trim'
import { diffMembers } from '../lib/diff-members'
import { sumWeights } from '../lib/sum-weights'
import {
  type PascalWallLike,
  localToWorld,
  wallHeightFromPascalWall,
  wallLengthFromPascalWall,
} from '../lib/wall-frame'
import { wallLevelElevation_mm } from '../lib/level-elevation'
import type { SceneLike } from '../lib/scene-walk'
import {
  makeSlabElevationFn,
  type SlabElevationForWallFn,
} from '../lib/slab-elevation'
import { getInheritedStudPositions_mm } from '../lib/stacked-walls'
import { findStudCandidatesAlongWall } from '../lib/stud-candidates'
import { isPanelizationRunning } from './panelization-pass'
import {
  computeOpeningLayout,
  fieldStudExcluded,
  type OpeningInputForLayout,
  type OpeningLayoutResult,
} from '../lib/opening-layout'

interface DesiredMember {
  role: CFSMember['role']
  sectionId: CFSSectionId
  start: CFSPoint3D
  end: CFSPoint3D
  /** Rotation of the cross-section about the member axis, degrees. Used to
   *  flip the C's open side so the flanges face inward at the start-end
   *  chord. Defaults to 0 — only set by the start chord (and the start-side
   *  promoted king when an opening sits at the wall edge). */
  orientation_deg?: number
  /** Set when the member was generated by an opening; null for chords/tracks/field studs. */
  sourceOpeningId: string | null
}

/**
 * Convert a world-space open direction (where the chord's C should open
 * in plan) into the cross-section rotation `orientation_deg` that the
 * extrusion cache and member-orientation matrix expect.
 *
 * The chord's mesh basis (set by `member-orientation.ts` for a vertical
 * stud) is: mesh +X = -wallDir, mesh +Y = wallFrame.normal where
 * normal = (-wallDir.z, wallDir.x). The polygon's open direction is
 * mesh +X at orientation_deg = 0. Rotating by `orient` puts the open
 * direction at `(cos(orient), sin(orient))` in the (mesh X, mesh Y)
 * plane, which in world is `mesh_X_world * cos + mesh_Y_world * sin`.
 * Solving for `orient`:
 *   cos = open · mesh_X_world  =  -(open · wallDir)
 *   sin = open · mesh_Y_world  =   open · normal
 */
function chordOrientationDeg(
  wallDir: { x: number; z: number },
  openDir: { x: number; z: number },
): number {
  const normalX = -wallDir.z
  const normalZ = wallDir.x
  const cosC = -(openDir.x * wallDir.x + openDir.z * wallDir.z)
  const sinC = openDir.x * normalX + openDir.z * normalZ
  const rad = Math.atan2(sinC, cosC)
  const deg = (rad * 180) / Math.PI
  if (deg > 180) return deg - 360
  if (deg < -180) return deg + 360
  return deg
}

function generateUuid(): string {
  const c: { randomUUID?: () => string } = (globalThis as { crypto?: { randomUUID?: () => string } }).crypto ?? {}
  if (typeof c.randomUUID === 'function') return c.randomUUID()
  const hex = (n: number) => Math.floor(Math.random() * 16 ** n).toString(16).padStart(n, '0')
  return `${hex(8)}-${hex(4)}-4${hex(3)}-a${hex(3)}-${hex(12)}`
}

function buildDesiredMembers(
  wall: PascalWallLike,
  framing: CFSWallFraming,
  settings: CFSProjectSettings,
  studSection: CFSSection,
  trackSection: CFSSection,
  ownsStartChord: boolean,
  ownsEndChord: boolean,
  openingLayout: OpeningLayoutResult,
  levelElevation_mm: number,
  /** Field-stud positions inherited from the wall directly below, if any.
   *  When non-null, these replace the default spacing-based computation
   *  so studs on the upper wall sit directly above the lower wall's studs
   *  (stack-load alignment per CFS detailing best practice). */
  inheritedFieldStudPositions_mm: number[] | null,
  /** L/T-corner lap: butt ends are shortened by the through wall's web
   *  depth so chord studs sit adjacent rather than overlapping. T-through
   *  walls additionally emit a chord-class stud at each T-post position
   *  the butting wall fastens into. */
  trim: WallTrim,
): DesiredMember[] {
  const length_mm = wallLengthFromPascalWall(wall)
  const height_mm =
    framing.wallHeight_mm ?? wallHeightFromPascalWall(wall)
  const spacing_mm = framing.studSpacing_mm ?? settings.defaultStudSpacing_mm
  const desired: DesiredMember[] = []
  const z = levelElevation_mm

  const startX = trim.startTrim_mm
  const endX = length_mm - trim.endTrim_mm
  const trimmedSpan_mm = Math.max(0, endX - startX)

  // L-butt lateral offset: shift every member uniformly in plan so the
  // butting wall's outer face is flush with the through wall's outer
  // face (instead of straddling the architectural centerline). Applied
  // to all members of this wall — tracks, chords, T-posts, field studs,
  // openings — since the wall moves together as a rigid frame.
  const ox = trim.lateralOffsetX_mm
  const oz = trim.lateralOffsetZ_mm
  const offsetPoint = (p: CFSPoint3D): CFSPoint3D => ({
    x_mm: p.x_mm + ox,
    y_mm: p.y_mm,
    z_mm: p.z_mm + oz,
  })

  // Step 2 — tracks. Tracks span the trimmed extent so the butt end stops
  // at the through wall's inside face.
  desired.push({
    role: 'top-track',
    sectionId: trackSection.id,
    start: offsetPoint(localToWorld(wall, { x_mm: startX, y_mm: height_mm, z_mm: 0 }, z)),
    end: offsetPoint(localToWorld(wall, { x_mm: endX, y_mm: height_mm, z_mm: 0 }, z)),
    sourceOpeningId: null,
  })
  desired.push({
    role: 'bottom-track',
    sectionId: trackSection.id,
    start: offsetPoint(localToWorld(wall, { x_mm: startX, y_mm: 0, z_mm: 0 }, z)),
    end: offsetPoint(localToWorld(wall, { x_mm: endX, y_mm: 0, z_mm: 0 }, z)),
    sourceOpeningId: null,
  })

  // Step 3 — chord studs at each (trimmed) end (subject to corner-ownership).
  // When an opening sits at the wall edge (§1.4 edge-collapse), the chord at
  // that end is promoted to role `king-stud` rather than emitting a separate
  // king. At butt ends `ownsXChord` will be true because the chord sits inside
  // the through wall's chord (different plan position, no merge).
  //
  // Orientation: the BUTT chord stud is rotated so its C-section's open
  // mouth faces perpendicular to its own wall, toward the through wall's
  // body — matches the real CFS detail the user confirmed via on-site
  // photos. THROUGH chords and FREE-END chords keep the default "open
  // along own wall axis into the body" orientation (180° at start, 0°
  // at end). The peerBodyDirection on EndJunction carries the world-space
  // direction we want the butt's C to face.
  const wallDir = wallDirection(wall)
  for (const [x, owns, promoteToKing, isStart, junction] of [
    [startX, ownsStartChord, openingLayout.promoteStartChordToKing, true, trim.startJunction] as const,
    [endX, ownsEndChord, openingLayout.promoteEndChordToKing, false, trim.endJunction] as const,
  ]) {
    if (!owns) continue
    const role: CFSMemberRole = promoteToKing ? 'king-stud' : 'chord-stud'
    const isButt = junction.kind === 'L-butt' || junction.kind === 'T-butt'
    const orientation_deg = isButt && junction.peerBodyDirection
      ? chordOrientationDeg(wallDir, junction.peerBodyDirection)
      : (isStart ? 180 : 0)
    desired.push({
      role,
      sectionId: studSection.id,
      start: offsetPoint(localToWorld(wall, { x_mm: x, y_mm: 0, z_mm: 0 }, z)),
      end: offsetPoint(localToWorld(wall, { x_mm: x, y_mm: height_mm, z_mm: 0 }, z)),
      orientation_deg,
      sourceOpeningId: null,
    })
  }

  // Step 3.5 — T-posts. Each peer butting into our interior gets a chord-
  // class stud on this wall at its junction x. Modelled as `chord-stud`
  // because that's structurally what it is — full height, takes the load
  // the butting wall transfers in.
  for (const post of trim.tPosts) {
    desired.push({
      role: 'chord-stud',
      sectionId: studSection.id,
      start: offsetPoint(localToWorld(wall, { x_mm: post.positionAlongWall_mm, y_mm: 0, z_mm: 0 }, z)),
      end: offsetPoint(localToWorld(wall, { x_mm: post.positionAlongWall_mm, y_mm: height_mm, z_mm: 0 }, z)),
      sourceOpeningId: null,
    })
  }

  // Step 4 — field studs, minus those displaced by openings (§1.4
  // stud-role coalescing) or by T-posts within ±half-spacing. When the
  // wall sits above another wall with a matching plan footprint, inherit
  // that wall's stud positions so axial load transfers straight down
  // (stack-load alignment). Inherited positions outside the trimmed span
  // are filtered out — the butt end has no room for them.
  const halfSpacing = spacing_mm / 2
  const tPostXs = trim.tPosts.map((p) => p.positionAlongWall_mm)
  const inTrimmedSpan = (x: number) => x > startX + 1 && x < endX - 1
  const nearTPost = (x: number) =>
    tPostXs.some((tx) => Math.abs(x - tx) < halfSpacing)
  const rawFieldXs =
    inheritedFieldStudPositions_mm ??
    findStudCandidatesAlongWall(spacing_mm, trimmedSpan_mm).map((x) => x + startX)
  for (const x of rawFieldXs) {
    if (!inTrimmedSpan(x)) continue
    if (nearTPost(x)) continue
    if (fieldStudExcluded(x, openingLayout.fieldStudExclusionRanges)) continue
    desired.push({
      role: 'stud',
      sectionId: studSection.id,
      start: offsetPoint(localToWorld(wall, { x_mm: x, y_mm: 0, z_mm: 0 }, z)),
      end: offsetPoint(localToWorld(wall, { x_mm: x, y_mm: height_mm, z_mm: 0 }, z)),
      sourceOpeningId: null,
    })
  }

  // Step 5 — opening-derived members (kings, jambs, headers, sills,
  // sill-tracks, cripples). The pure layout produces wall-local x/y; we
  // project to world here.
  for (const m of openingLayout.members) {
    desired.push({
      role: m.role,
      sectionId: m.sectionId,
      start: offsetPoint(localToWorld(wall, { x_mm: m.startX_mm, y_mm: m.startY_mm, z_mm: 0 }, z)),
      end: offsetPoint(localToWorld(wall, { x_mm: m.endX_mm, y_mm: m.endY_mm, z_mm: 0 }, z)),
      sourceOpeningId: m.sourceOpeningId,
    })
  }

  return desired
}

function materialiseDesired(framing: CFSWallFraming, desired: DesiredMember[]): CFSMember[] {
  return desired.map((d) =>
    CFSMember.parse({
      type: 'cfs_member',
      id: generateUuid(),
      parentId: framing.id,
      role: d.role,
      sectionId: d.sectionId,
      start: d.start,
      end: d.end,
      orientation_deg: d.orientation_deg ?? 0,
    }),
  )
}

function collectChildOpenings(
  nodes: Record<string, AnyNode>,
  framingId: string,
): CFSOpening[] {
  const out: CFSOpening[] = []
  for (const n of Object.values(nodes)) {
    if (
      (n as { type?: string }).type === 'cfs_opening' &&
      (n as { parentId?: string }).parentId === framingId
    ) {
      out.push(n as unknown as CFSOpening)
    }
  }
  out.sort((a, b) => a.positionAlongWall_mm - b.positionAlongWall_mm)
  return out
}

function toLayoutInputOpenings(
  openings: CFSOpening[],
): OpeningInputForLayout[] {
  return openings.map((o) => ({
    id: o.id as unknown as string,
    openingType: o.openingType,
    positionAlongWall_mm: o.positionAlongWall_mm,
    width_mm: o.roughDimensions.width_mm,
    height_mm: o.roughDimensions.height_mm,
    sillHeight_mm: o.sillHeight_mm,
    headerType: o.headerTypeOverride ?? undefined,
  }))
}

/**
 * Build (role, start, end) hash key matching `diff-members.ts`. We compute it
 * locally to avoid exporting an internal helper just for this attribution
 * pass; the constants here mirror `POS_TOLERANCE_MM = 1` from diff-members.
 */
function memberAttributionKey(m: { role: CFSMember['role']; start: CFSPoint3D; end: CFSPoint3D }): string {
  const r = (v: number) => Math.round(v)
  return `${m.role}|${r(m.start.x_mm)},${r(m.start.y_mm)},${r(m.start.z_mm)}|${r(m.end.x_mm)},${r(m.end.y_mm)},${r(m.end.z_mm)}`
}

function childrenOfType<T>(
  nodes: Record<string, AnyNode>,
  parentId: string,
  type: string,
): T[] {
  const out: T[] = []
  for (const n of Object.values(nodes)) {
    if ((n as { parentId?: string }).parentId === parentId && (n as { type?: string }).type === type) {
      out.push(n as unknown as T)
    }
  }
  return out
}

interface JunctionPeerCollection {
  ownSceneIndex: number
  peers: JunctionPeer[]
}

/**
 * Walk every other CFS wall framing and build the richer peer descriptor that
 * `corner-trim.computeWallTrim` consumes — scene insertion index (for the
 * "first-placed runs through" L-corner rule), full peer wall extents (for
 * T-junction detection where a peer endpoint lands on our interior), and the
 * peer's stud web depth (the trim amount when we butt into it).
 */
function collectJunctionPeers(
  scene: SceneLike,
  ownFramingId: string,
  library: CFSMemberLibrary,
  settings: CFSProjectSettings,
  slabFn: SlabElevationForWallFn,
): JunctionPeerCollection {
  const peers: JunctionPeer[] = []
  let ownSceneIndex = -1
  let index = -1
  for (const n of Object.values(scene.nodes)) {
    const t = (n as { type?: string }).type
    if (t !== 'cfs_wall_framing') continue
    index += 1
    const framing = n as unknown as CFSWallFraming
    if (framing.id === ownFramingId) {
      ownSceneIndex = index
      continue
    }
    const wall = scene.nodes[framing.parentId] as unknown as
      | PascalWallLike
      | undefined
    if (!wall || !wall.start || !wall.end) continue
    const peerLength_mm = wallLengthFromPascalWall(wall)
    if (peerLength_mm === 0) continue
    const studSectionId = framing.studSectionId ?? settings.defaultStudSection
    const studSection = library.sections.find((s) => s.id === studSectionId)
    // Fall back to the project's default section if we cannot resolve.
    // The peer is still real geometrically; we just have no exact figures.
    const defaultSection = library.sections.find(
      (s) => s.id === settings.defaultStudSection,
    )
    const webDepth_mm =
      studSection?.properties.webDepth_mm ??
      defaultSection?.properties.webDepth_mm ??
      0
    const flangeWidth_mm =
      studSection?.properties.flangeWidth_mm ??
      defaultSection?.properties.flangeWidth_mm ??
      0
    const peerElevation_mm =
      wallLevelElevation_mm(scene, wall.id, slabFn) +
      Math.max(0, slabFn(wall.id))
    peers.push({
      framingId: framing.id,
      sceneIndex: index,
      start: chordPositionFromWorld(
        localToWorld(wall, { x_mm: 0, y_mm: 0, z_mm: 0 }, peerElevation_mm),
      ),
      end: chordPositionFromWorld(
        localToWorld(
          wall,
          { x_mm: peerLength_mm, y_mm: 0, z_mm: 0 },
          peerElevation_mm,
        ),
      ),
      direction: wallDirection(wall),
      studWebDepth_mm: webDepth_mm,
      studFlangeWidth_mm: flangeWidth_mm,
    })
  }
  return { ownSceneIndex, peers }
}

function collectPeerChordPositions(
  scene: SceneLike,
  excludeFramingId: string,
  slabFn: SlabElevationForWallFn,
): import('../lib/corner-detect').ChordCandidate[] {
  const peers: import('../lib/corner-detect').ChordCandidate[] = []
  for (const n of Object.values(scene.nodes)) {
    const t = (n as { type?: string }).type
    if (t !== 'cfs_wall_framing') continue
    const framing = n as unknown as CFSWallFraming
    if (framing.id === excludeFramingId) continue
    const wall = scene.nodes[framing.parentId] as unknown as
      | PascalWallLike
      | undefined
    if (!wall || !wall.start || !wall.end) continue
    const length_mm = wallLengthFromPascalWall(wall)
    // Peer chord candidates carry both their world y (so cross-level
    // chord coincidences don't false-merge) and their plan direction
    // (so an L-corner where two perpendicular walls meet keeps both
    // chords — doubled-chord — while two collinear walls sharing an
    // endpoint still merge to one).
    const peerElevation_mm =
      wallLevelElevation_mm(scene, wall.id, slabFn) +
      Math.max(0, slabFn(wall.id))
    const dir = wallDirection(wall)
    peers.push({
      framingId: framing.id,
      position: chordPositionFromWorld(
        localToWorld(wall, { x_mm: 0, y_mm: 0, z_mm: 0 }, peerElevation_mm),
      ),
      direction: dir,
    })
    peers.push({
      framingId: framing.id,
      position: chordPositionFromWorld(
        localToWorld(
          wall,
          { x_mm: length_mm, y_mm: 0, z_mm: 0 },
          peerElevation_mm,
        ),
      ),
      direction: dir,
    })
  }
  return peers
}

interface FramingProcessResult {
  framingId: CFSWallFramingId
  status: 'ok' | 'no-library' | 'no-wall' | 'unresolved-section' | 'zero-length-wall'
  totalWeight_kg?: number
  memberCount?: number
  /** Opening ids that could not be placed (too wide, off the wall, etc.). */
  invalidOpeningIds?: string[]
}

/**
 * Re-entry guard. Each `useScene.createNode` inside this pass calls `set()`
 * synchronously, which fires every Zustand subscriber — including the one
 * that drives this very pass. Without the guard, creating member 1 of N
 * triggers a recursive runFramingPass that sees the framing still dirty,
 * tries to create members 2..N, recurses again on member 2, and so on
 * until the stack overflows around member 10–15. The fix: nested calls
 * return early; the outermost call completes naturally and the post-pass
 * subscriber tick (after we clear the dirty marker) becomes a no-op.
 */
let isRunning = false

/**
 * Process every dirty `cfs_wall_framing` id. Pure orchestrator: takes the
 * stores it needs as references, returns a per-framing status array. Idempotent.
 */
export function runFramingPass(): FramingProcessResult[] {
  if (isRunning) return []
  // Yield to the panelization pass while it's writing panels and
  // member.panelId. Each createNode inside panelization markDirties the
  // parent framing, which would re-fire this subscriber and let the
  // framing pass overwrite the planner's track splits / panel assignments
  // mid-flight. The framing pass will run cleanly on the next scene
  // change after panelization finishes.
  if (isPanelizationRunning()) return []
  isRunning = true
  try {
    return runFramingPassInner()
  } finally {
    isRunning = false
  }
}

function runFramingPassInner(): FramingProcessResult[] {
  const sceneState = useScene.getState()
  const cfsState = useCFS.getState()
  const settings = getProjectSettings(sceneState)
  const library = getActiveLibrary(cfsState)

  const results: FramingProcessResult[] = []

  // Snapshot dirty ids that match our type. We process whether or not we have
  // a library so that the status return value can drive inspector messaging.
  const dirty = Array.from(sceneState.dirtyNodes)
  const framingIds: CFSWallFramingId[] = []
  for (const id of dirty) {
    const node = sceneState.nodes[id]
    if (!node) continue
    if ((node as { type?: string }).type === 'cfs_wall_framing') {
      framingIds.push((node as unknown as CFSWallFraming).id)
    }
  }

  for (const framingId of framingIds) {
    const framing = sceneState.nodes[framingId as unknown as AnyNodeId] as unknown as
      | CFSWallFraming
      | undefined
    if (!framing) {
      sceneState.clearDirty(framingId as unknown as AnyNodeId)
      continue
    }

    const wall = sceneState.nodes[framing.parentId as unknown as AnyNodeId] as unknown as
      | PascalWallLike
      | undefined
    if (!wall || !Array.isArray(wall.start) || !Array.isArray(wall.end)) {
      results.push({ framingId, status: 'no-wall' })
      sceneState.clearDirty(framingId as unknown as AnyNodeId)
      continue
    }

    if (wallLengthFromPascalWall(wall) === 0) {
      results.push({ framingId, status: 'zero-length-wall' })
      sceneState.clearDirty(framingId as unknown as AnyNodeId)
      continue
    }

    if (!settings || !library) {
      // Per §5.1 step 1: abort the pass when prerequisites are missing.
      // Leave the framing dirty so a later pass picks it up after settings/library hydrate.
      results.push({ framingId, status: 'no-library' })
      continue
    }

    const studId = framing.studSectionId ?? settings.defaultStudSection
    const trackId = framing.trackSectionId ?? settings.defaultTrackSection
    const studSection = library.sections.find((s) => s.id === studId)
    const trackSection = library.sections.find((s) => s.id === trackId)
    if (!studSection || !trackSection) {
      results.push({ framingId, status: 'unresolved-section' })
      sceneState.clearDirty(framingId as unknown as AnyNodeId)
      continue
    }

    // §multi-story fix: lift this wall's framing y-coordinates by the
    // cumulative elevation of its parent level. Without this the upper-
    // level walls produce members at the ground floor (Slice 9 bug).
    //
    // Slab fix: Pascal also lifts each wall's mesh by the slab thickness
    // beneath it (`wall-system.tsx` → `mesh.position.y = slabElevation`).
    // Studs must follow that lift or they pierce the slab from below;
    // upper levels must also include the slab in their cumulative stack.
    // We pass `slabElevationFromManager` so both effects are accounted
    // for — the level math reads slabs of *prior* levels (cumulative
    // stack), then we add the *this* wall's slab on top.
    //
    // The elevation is computed up-front so the corner-detect call below
    // sees the chord positions at their true world y — that's how stacked
    // walls (different levels, same plan) are kept independent rather
    // than falsely merging chord ownership.
    const wallId = (wall as PascalWallLike).id
    const sceneLike = sceneState as unknown as SceneLike
    const slabFn = makeSlabElevationFn(sceneLike)
    const levelBase_mm = wallLevelElevation_mm(sceneLike, wallId, slabFn)
    const thisWallSlab_mm = Math.max(0, slabFn(wallId))
    const elevation_mm = levelBase_mm + thisWallSlab_mm

    const peers = collectPeerChordPositions(sceneLike, framingId, slabFn)
    const wallLength_mm = wallLengthFromPascalWall(wall)
    const ownStartWorld = chordPositionFromWorld(
      localToWorld(wall, { x_mm: 0, y_mm: 0, z_mm: 0 }, elevation_mm),
    )
    const ownEndWorld = chordPositionFromWorld(
      localToWorld(wall, { x_mm: wallLength_mm, y_mm: 0, z_mm: 0 }, elevation_mm),
    )
    const wallDir = wallDirection(wall)

    // L/T-corner lap: classify each end and our interior. The butt end will
    // be shortened by the through wall's web depth; T-through walls get a
    // chord-class stud at the junction position.
    const junctions = collectJunctionPeers(
      sceneLike,
      framingId,
      library,
      settings,
      slabFn,
    )
    const trim = computeWallTrim({
      ownFramingId: framingId,
      ownSceneIndex: junctions.ownSceneIndex,
      ownStart: ownStartWorld,
      ownEnd: ownEndWorld,
      ownDirection: wallDir,
      peers: junctions.peers,
    })

    // Chord-ownership is checked at the *trimmed* end positions so the butt
    // wall's chord doesn't false-merge with the through wall's chord at the
    // architectural endpoint (where they'd test as coincident). The trimmed
    // position is offset by the through-wall web depth into our wall, well
    // outside any chord coincidence tolerance.
    const trimmedStartWorld = chordPositionFromWorld(
      localToWorld(wall, { x_mm: trim.startTrim_mm, y_mm: 0, z_mm: 0 }, elevation_mm),
    )
    const trimmedEndWorld = chordPositionFromWorld(
      localToWorld(
        wall,
        { x_mm: wallLength_mm - trim.endTrim_mm, y_mm: 0, z_mm: 0 },
        elevation_mm,
      ),
    )
    const ownsStart = isCornerOwned(framingId, trimmedStartWorld, wallDir, peers)
    const ownsEnd = isCornerOwned(framingId, trimmedEndWorld, wallDir, peers)

    // Slice 4: run the opening layout *before* building the desired list so
    // chord promotions, field-stud exclusions, and opening-derived members
    // all flow through the same diff.
    const openings = collectChildOpenings(sceneState.nodes, framingId)
    const headerDefault: CFSHeaderType =
      framing.defaultHeaderType ?? settings.defaultHeaderType
    const wallHeight_mm =
      framing.wallHeight_mm ?? wallHeightFromPascalWall(wall)
    const studSpacing_mm = framing.studSpacing_mm ?? settings.defaultStudSpacing_mm
    const openingLayout = computeOpeningLayout({
      wallLength_mm: wallLengthFromPascalWall(wall),
      wallHeight_mm,
      studSpacing_mm,
      studSection,
      trackSection,
      defaultHeaderType: headerDefault,
      openings: toLayoutInputOpenings(openings),
    })

    // Stack-load alignment: if a wall directly below shares this wall's
    // plan footprint (within 100 mm), inherit its field-stud positions
    // so studs stack vertically across levels (CFS best practice).
    const inheritedStudXs = getInheritedStudPositions_mm(
      sceneLike,
      wall,
      settings.defaultStudSpacing_mm,
    )

    const desiredRaw = buildDesiredMembers(
      wall,
      framing,
      settings,
      studSection,
      trackSection,
      ownsStart,
      ownsEnd,
      openingLayout,
      elevation_mm,
      inheritedStudXs,
      trim,
    )
    const desired = materialiseDesired(framing, desiredRaw)
    const existing = childrenOfType<CFSMember>(sceneState.nodes, framingId, 'cfs_member')

    // §5.5 — once panelization has placed CFSPanels under this framing, it
    // owns the tracks: top-track / bottom-track / sill-track get split into
    // one piece per panel, each piece carries the panel's id, and the
    // exporters key on those ids. If we let the framing pass diff tracks,
    // it would emit a single full-wall track per role (its desired shape),
    // delete every panel-aware split, and create one fresh full-wall
    // member per role with `panelId = null` — i.e., it would silently
    // un-panelize the wall on the next scene mutation. Filter both sides
    // of the diff so tracks are left to panelization. Plain studs,
    // headers, jambs, sills, cripples are unaffected because panelization
    // never splits those.
    const hasPanels = childrenOfType<{ id: string }>(
      sceneState.nodes,
      framingId,
      'cfs_panel',
    ).length > 0
    const TRACK_ROLES = new Set<CFSMember['role']>([
      'top-track',
      'bottom-track',
      'sill-track',
    ])
    const desiredForDiff = hasPanels
      ? desired.filter((m) => !TRACK_ROLES.has(m.role))
      : desired
    const existingForDiff = hasPanels
      ? existing.filter((m) => !TRACK_ROLES.has(m.role))
      : existing
    const diff = diffMembers(existingForDiff, desiredForDiff)

    // Build attribution map: hash → sourceOpeningId. Members with no source
    // opening are excluded from the map; openings ids point at strings here
    // because the desired-member entries hold a string-typed source id.
    const attribution = new Map<string, string>()
    for (let i = 0; i < desired.length; i += 1) {
      const desiredMember = desired[i]!
      const raw = desiredRaw[i]!
      if (!raw.sourceOpeningId) continue
      attribution.set(memberAttributionKey(desiredMember), raw.sourceOpeningId)
    }

    withBatchedUndo('cfs:framing-pass', () => {
      const liveScene = useScene.getState()
      for (const m of diff.toCreate) {
        liveScene.createNode(m as unknown as AnyNode, framingId as unknown as AnyNodeId)
      }
      for (const u of diff.toUpdate) {
        liveScene.updateNode(
          u.id as unknown as AnyNodeId,
          u.changes as unknown as Partial<AnyNode>,
        )
      }
      for (const id of diff.toDelete) {
        liveScene.deleteNode(id as unknown as AnyNodeId)
      }

      const finalMembers: CFSMember[] = [
        ...existing.filter(
          (m) => !diff.toDelete.includes(m.id as unknown as CFSMemberId),
        ),
        ...diff.toCreate,
      ]
      const totalWeight_kg = sumWeights(finalMembers, library)
      const cachedMemberCount = finalMembers.length
      liveScene.updateNode(framingId as unknown as AnyNodeId, {
        cachedTotalWeight_kg: totalWeight_kg,
        cachedMemberCount,
      } as unknown as Partial<AnyNode>)

      // Attribute final members back to their source openings so the inspector
      // and panelization (Slice 7) can find every generated member in O(1).
      const idsByOpening = new Map<string, CFSMemberId[]>()
      for (const opening of openings) {
        idsByOpening.set(opening.id as unknown as string, [])
      }
      for (const m of finalMembers) {
        const key = memberAttributionKey(m)
        const oid = attribution.get(key)
        if (!oid) continue
        const list = idsByOpening.get(oid)
        if (!list) continue
        list.push(m.id)
      }
      for (const opening of openings) {
        const next = idsByOpening.get(opening.id as unknown as string) ?? []
        const prev = (opening.generatedMemberIds ?? []) as CFSMemberId[]
        // Only update when the set has actually changed; otherwise we churn
        // the scene and re-fire the dirty subscriber for nothing.
        if (
          prev.length === next.length &&
          prev.every((id, i) => id === next[i])
        ) {
          continue
        }
        liveScene.updateNode(opening.id as unknown as AnyNodeId, {
          generatedMemberIds: next,
        } as unknown as Partial<AnyNode>)
      }

      results.push({
        framingId,
        status: 'ok',
        totalWeight_kg,
        memberCount: cachedMemberCount,
        invalidOpeningIds: openingLayout.invalidOpeningIds,
      })
    })

    // Clear opening dirty markers we picked up in this pass — they have been
    // consumed and the framing is now consistent with their state.
    for (const o of openings) {
      sceneState.clearDirty(o.id as unknown as AnyNodeId)
    }
    sceneState.clearDirty(framingId as unknown as AnyNodeId)
  }

  return results
}
